### ISSUE TITLE
这个固件特别好用啊

### ISSUE THREAD

**Issue by Jecvay** [DHDAXCW/NanoPi-R4S-2021#1]
真的很不错。

问个问题，32G 的TF卡，有没有什么办法做到以下两点

1. 现在刷好后只有几百兆空间给软件包，能否扩容
2. 升级固件的时候能不能不清空扩容部分的内容

**Comment by DHDAXCW** [comment]
这个问题先放一放，目前在用ubuntu20.04环境搭建编译，等好了再搞

**Comment by 331969102** [comment]
额。这个建议挺好的。。使用docker扩容
