### ISSUE TITLE
自动关机

### ISSUE THREAD

**Issue by ljtao020** [DHDAXCW/NanoPi-R4S-2021#10]
我用这个固件 凌晨3点左右会自动关机，为什么呢

**Comment by DHDAXCW** [comment]
是因为400MHz频率低了容易引起死机，现在问题找到了，你需要去系统→CPU Freq 那些频率改一下 0 最大1460000  最低816000
4  最大1800000  最低816000  应用保存就可以了，这样不会的。今天的版本因为99%的人都不会去调cpu调节
所以今天修改了，移除CPU Freq插件。明天版本就能用上了，不需要去调cpu  直接自动调节。不好意思哈
