### ISSUE TITLE
R4S 定时重启（怀疑是定时运行coremark）

### ISSUE THREAD

**Issue by Cyclonekid** [DHDAXCW/NanoPi-R4S-2021#107]
R4S 定时重启（打开了重启推送）发现每天早上凌晨4点重启
查看了crontab里面   每天4点定时运行cornmark进行跑分·····

然后手工在shell里面运行/bin/coremark 路由直接重启

**Comment by WOAZAA** [comment]
我也遇到了 不过是两次 凌晨1点和凌晨4点，，去计划任务里删掉coremark.sh一行后没在发生过重启

**Comment by Cyclonekid** [comment]
是的，我现在的做法就是直接计划任务里面禁止coremark运行·    这两天没有再发生重启的事情，我手里还有r2s，r2s没有这个问题

**Comment by WOAZAA** [comment]
更新到最近的版本后现在4点coremark.sh运行后不会重启了，但是4点运行后passwall，smartdns，Turbo ACC，微信推送等服务全都停止，DNS失效，网页上的重启功能失效，SSH上执行reboot也不行，只能物理拔电重启
现在依然需要删掉这条计划任务才能保证存活~
