### ISSUE TITLE
R4S 强迫症跪求精简版本！

### ISSUE THREAD

**Issue by silmee** [DHDAXCW/NanoPi-R4S-2021#134]
基本用的插件就那几个，看着这么多不用的贼难受
能不能出个精简的，插件通过插件库自己装

**Comment by DHDAXCW** [comment]
安排！明天

**Comment by silmee** [comment]
没找到啊，大佬


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月18日 09:44:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DHDAXCW/NanoPi-R4S-2021] R4S 强迫症跪求精简版本！ (Issue #134)




 
安排！明天
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lihuaye** [comment]
@DHDAXCW 大佬，能否在安排个极简版带docker的版本
