### ISSUE TITLE
端口转发貌似不起作用（公网ip）

### ISSUE THREAD

**Issue by 1090549930** [DHDAXCW/NanoPi-R4S-2021#14]
也可能是我操作原因（？）

**Comment by DHDAXCW** [comment]
我用的没问题

**Comment by 1090549930** [comment]
10000和20000端口有占用吗我用的这2个

**Comment by 1090549930** [comment]
我试了upnp也不行

**Comment by 1090549930** [comment]
![image](https://user-images.githubusercontent.com/41770373/108520418-9f534f80-7305-11eb-8c43-52889bff779b.png)
这里有问题吗，求教

**Comment by 1090549930** [comment]
![image](https://user-images.githubusercontent.com/41770373/108520418-9f534f80-7305-11eb-8c43-52889bff779b.png)
这里有问题吗，求教

**Comment by DHDAXCW** [comment]
可能是，明天我查查问题吧

**Comment by 1090549930** [comment]
谢谢了a

**Comment by DHDAXCW** [comment]
用iptables转发，你的 iptables没放行吧

**Comment by DHDAXCW** [comment]
![Uploading image.png…]()

**Comment by DHDAXCW** [comment]
![image](https://user-images.githubusercontent.com/74764072/108522679-0ffb6b80-7308-11eb-86d1-50687b0089f5.png)

**Comment by DHDAXCW** [comment]
![image](https://user-images.githubusercontent.com/74764072/108522927-4c2ecc00-7308-11eb-8d25-dd77d76b1600.png)
![1c2c60ef2180c3191dc752d724eea4b](https://user-images.githubusercontent.com/74764072/108522962-581a8e00-7308-11eb-9432-0365cb56a861.jpg)

**Comment by 1090549930** [comment]
iptables转发没用过，，，以前都是在防火墙里面添加转发

**Comment by xbclub** [comment]
能否提供详细的转发步骤，与验证方式和结果

**Comment by 1090549930** [comment]
> 能否提供详细的转发步骤，与验证方式和结果

![image](https://user-images.githubusercontent.com/41770373/108582716-eaa24800-736f-11eb-93f8-6efb4dbd6cff.png)
哪有什么步骤的，像这样，以前我也都是怎么转发的，求教谢谢
另外没用过iptables..

**Comment by hongye1990** [comment]
我的也有点问题，虽然可以转发，但是只能从其他的外部网络（比如说手机热点）访问到被转发的端口，如果直接从内网访问是不可以的。

**Comment by 1090549930** [comment]
> 我的也有点问题，虽然可以转发，但是只能从其他的外部网络（比如说手机热点）访问到被转发的端口，如果直接从内网访问是不可以的。

还真是，我这边用流量也行

**Comment by xbclub** [comment]
traceroute 或者tracert 看下路由
