### ISSUE TITLE
每个一两天就死机

### ISSUE THREAD

**Issue by AEGEGE** [DHDAXCW/NanoPi-R4S-2021#15]
请问有遇到过这种情况吗？ssh无法连接，web无法连接，网络不通，重新插拔下电源就恢复了

**Comment by AEGEGE** [comment]
重启可以解决问题

**Comment by DHDAXCW** [comment]
你是哪个版本？如果是19版，不能直接卡升级，要卡刷，先卡刷低格，再卡刷。教程在主页下面有

**Comment by DHDAXCW** [comment]
还有一个电源问题，换个试试

**Comment by AEGEGE** [comment]
刷了3，4个版本都有这个问题···基本上2-3天就会死机一次，sys灯不亮，wan和lan灯常亮，其他人的固件也这样，难道是硬件问题？

**Comment by DHDAXCW** [comment]
是电源问题，你换个试试

**Comment by AEGEGE** [comment]
好的，我试试，谢谢
