### ISSUE TITLE
IPSec VPN连接后无法访问路由本身

### ISSUE THREAD

**Issue by hteane** [DHDAXCW/NanoPi-R4S-2021#16]
Softether怎么都用不了只有内网能连接所以改IPSec了，可以连接并且可以走路由的数据扶墙，但是就是不能访问路由本身的管理页面，连带其他端口号的QBT，Aria2也不行，但无线AP的的后台管理地址可以连接上，不知道是不是BUG，麻烦能不能看看呀？LUCI界面的IPSEC配置项就那么几个，搞不清楚问题出在哪。另外好像默认也不是用的路由的DHCP，然后连接上了路由的ip分配里看不到分配给通过vpn连接的设备，手机上能看到分配的ip是路由同网断的。另外iphone锁屏vpn连接就自动断了，不知道是ios的原因还是vpn server的原因。

**Comment by DHDAXCW** [comment]
可以实现从tun 改到tap。tun下把路由配置好也是可以实现的

**Comment by hteane** [comment]
具体怎么操作呀？求教，感恩~这是目前最后一个需求了

**Comment by hteane** [comment]
openvpn搞定，这个关了
