### ISSUE TITLE
关于ulimit设置的问题

### ISSUE THREAD

**Issue by AEGEGE** [DHDAXCW/NanoPi-R4S-2021#19]
关于系统ulimit nofile只是默认的1024，查了一下相关资料不能像开启发行版的linux修改/etc/securty/limits来永久生效，是否有其他方法修改？

**Comment by DHDAXCW** [comment]
先赋权限然后去修改

**Comment by AEGEGE** [comment]
具体方法？可以像其他linux发行版那样设置？
