### ISSUE TITLE
大佬可以加个去广告插件吗？

### ISSUE THREAD

**Issue by ljtao020** [DHDAXCW/NanoPi-R4S-2021#21]
大佬可以加个去广告插件吗？AdGuard Home我用着不太正常，监听端口会自己变回53，然后就傻了

**Comment by DHDAXCW** [comment]
为了不影响体验，暂时没有这个考虑加上

**Comment by lingzhuxin** [comment]
好像是因为要去防火墙里自己注释掉那两个53接口

**Comment by rushboss** [comment]
> 
> 
> 大佬可以加个去广告插件吗？AdGuard Home我用着不太正常，监听端口会自己变回53，然后就傻了

luci-app-dnsfilter https://github.com/garypang13/luci-app-dnsfilter/releases 试试这个
