### ISSUE TITLE
可以加个签到插件吗

### ISSUE THREAD

**Issue by 1090549930** [DHDAXCW/NanoPi-R4S-2021#22]
大佬可以加个签到插件吗

**Comment by DHDAXCW** [comment]
方便提供源码？我这不清楚是哪个。除了京东签到，其他我不知道了。狗签到这个不好搞，收费的

**Comment by 1090549930** [comment]
啊这，我以前也用的是狗签到，收费就没用过了...

________________________________
发件人: 骷髅头 <notifications@github.com>
发送时间: 2021年2月27日 18:33
收件人: DHDAXCW/NanoPi-R4S-2021 <NanoPi-R4S-2021@noreply.github.com>
抄送: 1090549930 <o1090549930o@outlook.com>; Author <author@noreply.github.com>
主题: Re: [DHDAXCW/NanoPi-R4S-2021] 可以加个签到插件吗 (#22)


方便提供源码？我这不清楚是哪个。除了京东签到，其他我不知道了。狗签到这个不好搞，收费的

―
