### ISSUE TITLE
许个愿：希望有朝一日支持samba4

### ISSUE THREAD

**Issue by hteane** [DHDAXCW/NanoPi-R4S-2021#29]
Time Machine over samba4还挺有诱惑力的，samba36怎么配置都搞不定....哎

**Comment by DHDAXCW** [comment]
我.....我也不会

**Comment by hteane** [comment]
我有看到samba4编辑配置文件的教程，但是要配合avahi daemon，然后我用samba36试了不成功，samba4跟samba36冲突，卸载samba36装samba4又没有luci界面了有点麻烦，希望大佬有空可以了解下哈哈哈
