### ISSUE TITLE
为什么要移除docker ，后期再加入？

### ISSUE THREAD

**Issue by coppea** [DHDAXCW/NanoPi-R4S-2021#30]
是兼容问题吗，我最近正在使用docker

**Comment by DHDAXCW** [comment]
先试试移除，对udp和ipv6会怎么样。后天会回归的。不好意思哈

**Comment by amaztony** [comment]
网络接口的那的docker是怎么桥接的，我好像把那个接口删了，现在容器启动不来，不知道有没有关系

**Comment by coppea** [comment]
> 先试试移除，对udp和ipv6会怎么样。后天会回归的。不好意思哈

不知骷髅头大佬什么时候再加进去

**Comment by DHDAXCW** [comment]
今天就加。 明天就可以用了。最近在搞r2s支持aes解密。。。搞得鼻子流血了😭

**Comment by coppea** [comment]
谢谢，辛苦大佬了
