### ISSUE TITLE
3月10日版本，Passwall  SSR 代理 UDP 好像有问题 

### ISSUE THREAD

**Issue by liuquanqing** [DHDAXCW/NanoPi-R4S-2021#32]
3月7日之前的版本是正常的。现在玩命运2进不去了。

SS 不支持 fake IP ，就用的 SSR ，薯条没有 v2ray 了。

**Comment by DHDAXCW** [comment]
V2ray被xray代替去了。你有v2ray可以用的，求你特，哪个ssr udp真的失效了？我今晚就检查一下看看吧。顺便说下你用的是哪个插件？

**Comment by liuquanqing** [comment]
> V2ray被xray代替去了。你有v2ray可以用的。还有，哪个ssr udp真的失效了？我今晚就检查一下看看吧。顺便说下你用的是哪个插件？

我现在用的机场没有 v2ray 了，用的 passwall fake IP  进不去游戏， DOH  能进游戏但是进不了站点，卡在地图页

**Comment by DHDAXCW** [comment]
好的，谢谢反馈哈，我这就去检查一下

**Comment by liuquanqing** [comment]
> 好的，谢谢反馈哈，我这就去检查一下

好的，确认是 passwall 的问题，用 hello world SS 都能游戏代理成功。 passwall 这个 fakeip 不是很给力啊。
