### ISSUE TITLE
MAC地址会不断地变化

### ISSUE THREAD

**Issue by bg4drl** [DHDAXCW/NanoPi-R4S-2021#33]
WAN/LAN口的MAC地址重启就发生变化 这是大问题...

**Comment by DHDAXCW** [comment]
还有这情况？好我这就去看下。顺便报上固件版本哈

**Comment by bg4drl** [comment]
OpenWrt R21.2.1 (2021.03.09) / LuCI Master (git-21.035.34289-13f96d1)

**Comment by bg4drl** [comment]
OpenWrt R21.2.1 (2021.03.10) / LuCI Master (git-21.035.34289-13f96d1)
--
现在eth0何eth1置换后在尝试

**Comment by bg4drl** [comment]
eth0/eth1置换后没问题, 这个3/10已经确认. 
但不置换应该还是老样子 启动后随机跳跃mac地址

**Comment by bg4drl** [comment]
ARM内核普遍发生这个老大难问题 而X86重来没有这回事
家里的华为云雀摄像头也一样 想骂一声烂系统 哈哈哈

**Comment by DHDAXCW** [comment]
确实有点

**Comment by DHDAXCW** [comment]
这问题我明天下午去试试。另外大佬说过编译大群也提到过类似问题。
