### ISSUE TITLE
2021-03-18官方原生固件版本重设wan口的mac地址无效

### ISSUE THREAD

**Issue by aimuch** [DHDAXCW/NanoPi-R4S-2021#36]
2021-03-17版本重设wan口的mac地址无效，依旧用的是原mac地址

**Comment by bg4drl** [comment]
网线插拔一次 或renew

**Comment by aimuch** [comment]
> 网线插拔一次 或renew

没用

**Comment by DHDAXCW** [comment]
我等下午去看一下，谢谢反馈

**Comment by aimuch** [comment]
同步的源码有问题，klever1988/nanopi-openwrt的设置了mac地址也无效

**Comment by aimuch** [comment]
> 我等下午去看一下，谢谢反馈

同步的源码有问题，klever1988/nanopi-openwrt的设置了mac地址也无效

**Comment by choz333** [comment]
后续的R4S更新网口都互换？不过好像R4S互换好像没什么区别吧？

**Comment by DHDAXCW** [comment]
> 后续的R4S更新网口都互换？不过好像R4S互换好像没什么区别吧？

是lean源码导致的。还得等他修复才回来

**Comment by aimuch** [comment]
20以后的版本依然没解决，重设mac地址问题
![111620590-e27be200-8821-11eb-9d7c-158bf53c6a86](https://user-images.githubusercontent.com/17581911/111931501-49d1b480-8af6-11eb-80e3-7832168feeea.png)
