### ISSUE TITLE
请求加入华为随行5G USB驱动，有偿，急，谢

### ISSUE THREAD

**Issue by HonorWater** [DHDAXCW/NanoPi-R4S-2021#37]
我现在手里有一个 华为 5G 随行 Pro的上网设备，它本身是可以通过USB连接电脑，给电脑上网的。
但是我希望能把华为5G随行通过USB连接到r4s的USB口，作为WAN。了解下来缺失驱动，所以想请求你的帮忙。
我也知道你平时都是无私奉献，我这个需求比较小众，我愿意提供报酬来感谢你的协助。谢谢！
或者可以联系我tg: @autohan

**Comment by DHDAXCW** [comment]
我目前找不到这种驱动。如果你有可以留在这驱动源也行

**Comment by HonorWater** [comment]
已经找到方案了，直接USB插入之后，识别出eth2 之后，直接创建一个新接口就可以使用了。多谢了。

**Comment by DHDAXCW** [comment]
好，祝你好运
