### ISSUE TITLE
我是小白，请教大神一个关于wifi的问题

### ISSUE THREAD

**Issue by Evens3body** [DHDAXCW/NanoPi-R4S-2021#4]
你好，我的r2s、r4s都想用您的固件，但是最近有在软路由插wifi网卡的需求，结果就买了一个，我发现用您的固件没法驱动WiFi设备，usb网卡指示灯都没有亮，我买的网卡是AC1200，确定是官方固件支持的网卡，请教我该如何解决，谢谢

**Comment by DHDAXCW** [comment]
WiFi芯片型号留言，写这里

**Comment by Evens3body** [comment]
> WiFi芯片型号留言，写这里

Realtek 8812BU Wireless

**Comment by Evens3body** [comment]
Realtek 8812BU Wireless
谢谢！

骷髅头 <notifications@github.com> 于 2021年2月9日周二 15:27写道：

**Comment by DHDAXCW** [comment]
刚刚打上了驱动，等明天11版吧，如果没有反应直接问我

**Comment by Evens3body** [comment]
> 刚刚打上了驱动，等明天11版吧，如果没有反应直接问我

万分感谢
