### ISSUE TITLE
关于NFS管理的问题

### ISSUE THREAD

**Issue by hteane** [DHDAXCW/NanoPi-R4S-2021#5]
大神你好，我是从梅林刚换到Openwrt的小白，目前用的您的R4S2.6的固件，因为有局域网共享硬盘的需求，所以想把路由上的硬盘分享出去，但是通过网络储存-NFS管理的图形界面操作无论如何都不成功，我的理解是路由挂载的硬盘只需要在第一项分享目录里填好硬盘的挂载目录“/mnt/sda2”，用户“*”或者“192.168.2.0/24”，然后选项默认就可以的对吗？第二项的已挂载的目录需要添加条目和启用吗？google了一圈也没找到这个图形界面的设置教程，都是ssh命令启用和挂载的，我用的macbook，对ssh也不熟，想了解下究竟如何成功开启NFS。谢谢！

**Comment by hteane** [comment]
另外github我也是小白，想问个巨蠢的问题，最新的固件是在哪下载啊，go to files跳转的是code页面。。。。。没看到看起来像固件包的文件。。。。

**Comment by DHDAXCW** [comment]
看看这个版本能不能解决 https://github.com/DHDAXCW/NanoPi-R4S-2021/releases

**Comment by hteane** [comment]
请问下是直接在Openwrt里更新吗？我下载了ext4和squashfs两个sysupgrade的固件点更新，刷新固件后进去还是2.6点固件，应该是没有成功。是要重新刷TF卡么？

**Comment by DHDAXCW** [comment]
当然卡刷，但是不能恢复备份。重新设置最好

**Comment by hteane** [comment]
好的，了解啦，谢谢！明天试试，机场的服务器挂了现在刷不恢复配置的话没法订阅节点。。。

**Comment by hteane** [comment]
发现SMB协议的网络共享已经够用了不需要NFS了关了
