### ISSUE TITLE
4.12固件换三星TF卡后依旧半夜关机

### ISSUE THREAD

**Issue by tanglegg** [DHDAXCW/NanoPi-R4S-2021#62]
R4S+华为5V4A充电头，仅使用HELLOWORLD科学上网及去广告，目前就3.19固件使用正常，后面的固件刷了均半夜关机，时间大概在凌晨4点左右，怀疑是闪迪32G TF卡的问题，现购买全新三星EVO 64G TF刷4.12固件，依旧出现半夜关机情况，奇怪的是白天怎么使用都正常，半夜无使用待机却出现关机情况，目前换5V2.1A绿联充电头测试是否充电头存在问题，结果需要明天早上才知道，不过应该不是充电头的问题，因为只要换回3.19固件就不存在问题，麻烦博主查一下

**Comment by DHDAXCW** [comment]
用华为充电头不会激活快充的。你半夜死机正好是CPU开始跑分的时候了

**Comment by tanglegg** [comment]
> 用华为充电头不会激活快充的。你半夜死机正好是CPU开始跑分的时候了

不是5V2A和9V2A的快充头，只是固定的5V4A，双USB接口，用万用表测试，电压5V，电流在1-3.5A间，半夜跑分？跑什么分？都没人使用了，自己在那里拷机么？昨天用充电头测试，5V1A的充电头开不了机，5V1.5A的充电头开机后关机，要5V2A才能正常开机使用，你的意思是我的5V4A的华为充电头是有问题的？那为什么3.19的固件不出现半夜关机的情况，难道3.19后增加了半夜跑分的程序？没人使用跑分？用来挖矿么？

**Comment by DHDAXCW** [comment]
半夜是跑coremark，所以，别用我的了，省的麻烦ᥬ😂᭄我不管你用啥，我现在已经4天没掉线。总之。追求稳定，别瞎折腾。OK？

**Comment by DHDAXCW** [comment]
顺便说下，我1a也能开机，你机器有问题吧？
