### ISSUE TITLE
关闭动态超频

### ISSUE THREAD

**Issue by S1U** [DHDAXCW/NanoPi-R4S-2021#78]
`我的固件加了动态超频，不管热不热这是取决后台运行程序在跑什么`

不需要超频，即使是动态的，不稳定。在哪里关掉它？

**Comment by DHDAXCW** [comment]
我给你定制版本吧，取消频率

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/NanoPi-R4S-2021/releases/tag/2021.05.07-Lean2
