### ISSUE TITLE
可以装个腾讯云的ddns吗

### ISSUE THREAD

**Issue by 1090549930** [DHDAXCW/NanoPi-R4S-2021#89]
每次更新重新装感觉麻烦...，求预装搞一下

**Comment by DHDAXCW** [comment]
你有木有地址源码？

**Comment by 1090549930** [comment]
https://github.com/Tencent-Cloud-Plugins/tencentcloud-openwrt-plugin-ddns
谢谢

**Comment by 1090549930** [comment]
> 你有木有地址源码？
https://github.com/Tencent-Cloud-Plugins/tencentcloud-openwrt-plugin-ddns
谢谢

**Comment by DHDAXCW** [comment]
我更新了软件源,你可以从软件源查找.插件名luci-app-tencentddns,搜搜即可

**Comment by 1090549930** [comment]
嗯謝謝
